export const REPOSITORIES = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  SUPER_USER_REPOSITORY: 'SUPER_USER_REPOSITORY',
  LOGIN_TOKEN_REPOSITORY: 'LOGIN_TOKEN_REPOSITORY',
  FORGOT_PASSWORD_REPOSITORY: 'FORGOT_PASSWORD_REPOSITORY',
  COMPANY_REPOSITORY: 'COMPANY_REPOSITORY',
  COMPANY_USERS_REPOSITORY: 'COMPANY_USERS_REPOSITORY',
  USER_LOCATION_REPOSITORY: 'USER_LOCATION_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  ROLE_PERMISSION_REPOSITORY: 'ROLE_PERMISSION_REPOSITORY',
  PERMISSION_REPOSITORY: 'PERMISSION_REPOSITORY',
};